# Generated by Django 4.1.6 on 2023-03-22 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compilations', '0006_rename_author_compilation_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Member'), (1, 'Editor'), (2, 'Admin'), (3, 'Owner')], default=0)),
                ('compilation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compilations.compilation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='compilationmembership',
            constraint=models.UniqueConstraint(fields=('compilation', 'user'), name='compilation_membership_unique_constraint'),
        ),
    ]
