# Generated by Django 4.1.6 on 2023-04-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilation_memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compilationmembership',
            name='compilation_membership_unique_constraint',
        ),
        migrations.RemoveField(
            model_name='compilationmembership',
            name='role',
        ),
        migrations.AddField(
            model_name='compilationmembership',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
