# Generated by Django 4.1.6 on 2023-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0004_alter_compilation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
