# Generated by Django 4.1.6 on 2023-03-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_latitude_place_lat_rename_longitude_place_lon'),
        ('compilations', '0005_alter_compilation_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compilation',
            old_name='author',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='compilation',
            name='places',
            field=models.ManyToManyField(blank=True, to='places.place'),
        ),
    ]
