# Generated by Django 4.1.6 on 2023-04-04 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compilation_memberships', '0002_remove_compilationmembership_compilation_membership_unique_constraint_and_more'),
        ('compilations', '0006_rename_author_compilation_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilation',
            options={'default_permissions': [], 'permissions': [('change_compilation', 'Изменение данных коллекции'), ('change_compilation_places_list', 'Изменение списка точек в коллекции')]},
        ),
        migrations.AddField(
            model_name='compilation',
            name='members',
            field=models.ManyToManyField(blank=True, through='compilation_memberships.CompilationMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_compilations', to=settings.AUTH_USER_MODEL),
        ),
    ]
