# Generated by Django 4.1.6 on 2023-04-13 17:26

from django.db import migrations


def remove_permissions(apps, schema_editor):
    '''Reverse the above additions of permissions.'''
    ContentType = apps.get_model('contenttypes.ContentType')
    Permission = apps.get_model('auth.Permission')
    content_type = ContentType.objects.get(
        model='compilation',
        app_label='compilations',
    )
    Permission.objects.filter(
        content_type=content_type,
        codename__in=(
            'add_compilation',
            'change_compilation',
            'compilation.change_places_list',
            'compilation_edit',
            'compilations.change_compilation',
            'delete_compilation',
            'view_compilation',
        ),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('compilations', '0008_alter_compilation_options'),
    ]

    operations = [
        migrations.RunPython(remove_permissions, reverse_code=lambda apps, schema_editor: None),
        migrations.AlterModelOptions(
            name='compilation',
            options={
                'default_permissions': [],
                'permissions': [('compilation_change', 'Изменение данных коллекции'),
                    ('compilation_change_places_list', 'Изменение списка точек в коллекции')]
            },
        ),
    ]
