# Generated by Django 4.1.6 on 2023-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_latitude_place_lat_rename_longitude_place_lon'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['lat'], name='places_plac_lat_772665_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['lon'], name='places_plac_lon_bab6ae_idx'),
        ),
    ]
