# Generated by Django 4.1.6 on 2023-04-19 22:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos
from django.contrib.gis.geos import Point
from django.db import migrations


def fill_places_data(apps, schema_editor):
    Place = apps.get_model('places.Place')

    for place in Place.objects.all():
        place.location = Point(x=place.lon, y=place.lat)
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_places_plac_lat_772665_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point(0.0, 0.0),
                geography=True,
                srid=4326
            ),
            preserve_default=False,
        ),
        migrations.RunPython(fill_places_data, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_lat_772665_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_lon_bab6ae_idx',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lon',
        ),
    ]
