# Generated by Django 4.1.6 on 2023-04-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='location',
            new_name='geometry',
        ),
    ]
